name: Cypress API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # runs every Monday at 00:00 UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      GOREST_API_TOKEN: ${{ secrets.GOREST_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Notify Discord (completed)
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "📦 Cypress test job completed on `${{ github.ref_name }}`. Check results: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
